#!/usr/bin/env bash
#displays information about a file called school

if [ -e "school" ]
then
	echo "schoolfile exits"
	if [ -s "school" ]
	then
		"school file is not empty"
	else
		"school file is empty"
	fi

	if [  -f "school" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
