#!/usr/bin/env bash
#a Bash script that displays all active IPv4 IPs on the machine it’s executed on.
#So since i am using a sandbox it will show some ip different from local system

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
